tasks:
  - init: |
      docker-compose pull
      docker-compose build
  - command: |
      docker-compose up


ports:
  # JupyterLab  : Port 8889
  - port: 8889
    onOpen: open-browser
  # Hue         : Port 8888 using admin/admin
  - port: 8888
    onOpen: open-browser
  # Minio       : Port 9001 using savas/savas123
  - port: 9001
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
